name: Process FluSight Data

on:
  push:
    branches:
      - main
    paths:
      - 'model-output/**'
  workflow_dispatch:

jobs:
  process-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy pyarrow
        
    - name: Process FluSight data
      run: |
        python scripts/process_flusight_data.py
        
    - name: Upload processed data
      uses: actions/upload-artifact@v3
      with:
        name: processed-flusight-data
        path: processed_data/
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add processed_data/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update processed data" && git push)
