name: Build and Deploy Site

on:
  schedule:
    - cron: '0 12 * * 4'  # Thursdays 8 AM ET (12 PM UTC) - FluSight schedule
    - cron: '0 12 * * *'  # Daily at 8 AM ET (12 PM UTC) - NHSN schedule  
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  process-flusight:
    if: github.event.schedule == '0 12 * * 4' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout visualization repository
      uses: actions/checkout@v4
      
    - name: Clone FluSight forecast hub
      run: |
        git clone https://github.com/cdcepi/FluSight-forecast-hub.git
        echo "FluSight hub cloned, checking contents:"
        ls -la FluSight-forecast-hub/
      
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
    - name: Cache FluSight data
      uses: actions/cache@v4
      id: cache-flusight
      with:
        path: app/public/processed_data/
        key: flusight-${{ steps.date.outputs.date }}
        restore-keys: |
          flusight-
          
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy pyarrow tqdm logging typing requests
        
    - name: Process FluSight data
      run: |
        mkdir -p app/public/processed_data
        python scripts/process_flusight_data.py --hub-path ./FluSight-forecast-hub --output-path ./app/public/processed_data
        echo "Checking processed FluSight files:"
        ls -la app/public/processed_data/
        

  process-rsv:
    if: github.event.schedule == '0 12 * * 4' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout visualization repository
      uses: actions/checkout@v4
      
    - name: Clone RSV forecast hub
      run: |
        git clone https://github.com/HopkinsIDD/rsv-forecast-hub.git
        echo "RSV hub cloned, checking contents:"
        ls -la rsv-forecast-hub/
        echo "Target data files:"
        ls -la rsv-forecast-hub/target-data/ || echo "No target-data directory found"
        echo "Auxiliary data:"
        ls -la rsv-forecast-hub/auxiliary-data/ || echo "No auxiliary-data directory found"
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy pyarrow tqdm logging typing requests
        
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
    - name: Cache processed RSV data
      uses: actions/cache@v4
      id: cache-processed-rsv
      with:
        path: app/public/processed_data/rsv/
        key: processed-rsv-${{ steps.date.outputs.date }}
        restore-keys: |
          processed-rsv-
        
    - name: Process RSV data
      run: |
        mkdir -p app/public/processed_data/rsv
        python scripts/process_rsv_data.py --hub-path ./rsv-forecast-hub --output-path ./app/public/processed_data
        echo "Checking processed RSV files:"
        ls -la app/public/processed_data/rsv/
        

  process-nhsn:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout visualization repository
      uses: actions/checkout@v4
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy pyarrow tqdm logging typing requests
        
    - name: Cache processed NHSN data
      uses: actions/cache@v4
      id: cache-processed-nhsn
      with:
        path: app/public/processed_data/nhsn/
        key: processed-nhsn-${{ github.run_id }}
        restore-keys: |
          processed-nhsn-
        
    - name: Process NHSN data
      run: |
        mkdir -p app/public/processed_data/nhsn
        python scripts/process_nhsn_data.py --output-path ./app/public/processed_data --locations-path ./data/locations.csv
        echo "Checking processed NHSN files:"
        ls -la app/public/processed_data/nhsn/
        
    - name: Upload processed data
      uses: actions/upload-artifact@v4
      with:
        name: processed-nhsn-data
        path: app/public/processed_data/nhsn/
        if-no-files-found: error
        retention-days: 7

  build-and-deploy:  
    needs: [process-nhsn]
    if: always()
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'app/package-lock.json'
          
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          
      - name: Restore FluSight cache
        uses: actions/cache/restore@v4
        with:
          path: app/public/processed_data/
          key: flusight-${{ steps.date.outputs.date }}
          restore-keys: |
            flusight-
          
      - name: Restore RSV cache
        uses: actions/cache/restore@v4
        with:
          path: app/public/processed_data/rsv/
          key: processed-rsv-${{ steps.date.outputs.date }}
          restore-keys: |
            processed-rsv-
          
      - name: Download NHSN data
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: processed-nhsn-data
          path: app/public/processed_data/nhsn
          
      - name: Install dependencies
        working-directory: ./app
        run: npm ci
        
      - name: Clean
        working-directory: ./app
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
          
      - name: Build website
        working-directory: ./app
        run: |
          if [ "${{ github.repository }}" = "ACCIDDA/RespiLens-staging" ]; then
            npm run build:staging
          else
            npm run build
          fi
          
      - name: Copy index.html to 404.html for SPA routing
        working-directory: ./app
        run: cp dist/index.html dist/404.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./app/dist
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4