name: Process FluSight Data

on:
  schedule:
    # Run at 11 PM ET Wednesday (3 AM UTC Thursday) and 10 AM ET Thursday (2 PM UTC Thursday)
    - cron: '0 3 * * 4'
    - cron: '0 14 * * 4'
  workflow_dispatch:

jobs:
  process-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout visualization repository
      uses: actions/checkout@v3
      
    - name: Checkout FluSight-forecast-hub
      uses: actions/checkout@v3
      with:
        repository: 'cdcepi/FluSight-forecast-hub'
        path: 'FluSight-forecast-hub'
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy pyarrow tqdm
        
    - name: Process FluSight data
      run: |
        mkdir -p app/public/processed_data     # Change the output directory to be under app/public
        python scripts/process_flusight_data.py
      env:
        FLUSIGHT_HUB_PATH: './FluSight-forecast-hub'
        OUTPUT_PATH: './app/public/processed_data'   # Update the output path
        
    - name: Upload processed data
      uses: actions/upload-artifact@v4
      with:
        name: processed-flusight-data
        path: app/public/processed_data/
        retention-days: 1
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add app/public/processed_data/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update processed data")
        if [ $? -eq 1 ]; then
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
          git push
        fi
      env:
        PAT: ${{ secrets.PAT }}
