name: Process FluSight Data

on:
  schedule:
    - cron: '0 12 * * 4'  # Thursdays 8 AM ET (12 PM UTC)
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  process-flusight:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout visualization repository
      uses: actions/checkout@v4
      
    - name: Cache FluSight data
      uses: actions/cache@v4
      id: cache-flusight
      with:
        path: FluSight-forecast-hub
        key: flusight-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: |
          flusight-
    
    - name: Checkout FluSight-forecast-hub
      if: steps.cache-flusight.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: 'cdcepi/FluSight-forecast-hub'
        path: 'FluSight-forecast-hub'
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy pyarrow tqdm logging typing
        
    - name: Cache processed FluSight data
      uses: actions/cache@v4
      id: cache-processed-flusight
      with:
        path: app/public/processed_data/
        key: processed-flusight-${{ hashFiles('FluSight-forecast-hub/**/*.csv', 'FluSight-forecast-hub/**/*.parquet') }}
        
    - name: Process FluSight data
      if: steps.cache-processed-flusight.outputs.cache-hit != 'true'
      run: |
        mkdir -p app/public/processed_data
        python scripts/process_flusight_data.py --hub-path ./FluSight-forecast-hub --output-path ./app/public/processed_data
        echo "Checking processed files:"
        ls -la app/public/processed_data/
        
    - name: Upload processed data
      uses: actions/upload-artifact@v4
      with:
        name: processed-flusight-data
        path: app/public/processed_data/
        if-no-files-found: error
        retention-days: 7