name: Process RSV Data

on:
  schedule:
    - cron: '15 12 * * 4'  # Thursdays 8:15 AM ET (12:15 PM UTC)
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  process-rsv:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout visualization repository
      uses: actions/checkout@v4
      
    - name: Cache RSV data
      uses: actions/cache@v4
      id: cache-rsv
      with:
        path: rsv-forecast-hub
        key: rsv-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: |
          rsv-
    
    - name: Checkout RSV-forecast-hub
      if: steps.cache-rsv.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: 'HopkinsIDD/rsv-forecast-hub'
        path: 'rsv-forecast-hub'
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy pyarrow tqdm logging typing
        
    - name: Cache processed RSV data
      uses: actions/cache@v4
      id: cache-processed-rsv
      with:
        path: app/public/processed_data/rsv/
        key: processed-rsv-${{ hashFiles('rsv-forecast-hub/**/*.parquet') }}
        
    - name: Process RSV data
      if: steps.cache-processed-rsv.outputs.cache-hit != 'true'
      run: |
        mkdir -p app/public/processed_data
        python scripts/process_rsv_data.py --hub-path ./rsv-forecast-hub --output-path ./app/public/processed_data
        echo "Checking processed RSV files:"
        ls -la app/public/processed_data/rsv/
        
    - name: Upload processed data
      uses: actions/upload-artifact@v4
      with:
        name: processed-rsv-data
        path: app/public/processed_data/rsv/
        if-no-files-found: error
        retention-days: 7